//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomaticGamepad.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language_Chinese {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_Chinese() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutomaticGamepad.Properties.Language_Chinese", typeof(Language_Chinese).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 绑定状态： 的本地化字符串。
        /// </summary>
        internal static string binding_status {
            get {
                return ResourceManager.GetString("binding_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本文件不存在！{0} 的本地化字符串。
        /// </summary>
        internal static string file_not_exist {
            get {
                return ResourceManager.GetString("file_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件中无代码可执行！ 的本地化字符串。
        /// </summary>
        internal static string no_code {
            get {
                return ResourceManager.GetString("no_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未运行{0}应用！ 的本地化字符串。
        /// </summary>
        internal static string not_run {
            get {
                return ResourceManager.GetString("not_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择一个脚本 的本地化字符串。
        /// </summary>
        internal static string select_script {
            get {
                return ResourceManager.GetString("select_script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口标题不能为空！ 的本地化字符串。
        /// </summary>
        internal static string title_cannot_empty {
            get {
                return ResourceManager.GetString("title_cannot_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请不要操作太快！ 的本地化字符串。
        /// </summary>
        internal static string too_fast {
            get {
                return ResourceManager.GetString("too_fast", resourceCulture);
            }
        }
    }
}
